### ISSUE TITLE
Add react css components

### ISSUE THREAD

**Issue by ngzhian** [momomods/momomods#23]
If we are standardizing on material design we can use this: https://github.com/tleunen/react-mdl. It wraps https://getmdl.io/ into react components we can use.

**Comment by ngzhian** [comment]
I've added `react-mdl` to the repo, you can see example usage in https://github.com/momomods/momomods/blob/master/src/components/Drawer/Drawer.js :)

**Comment by nicholette** [comment]
Should we close this issue because we create components on the fly?
