### ISSUE TITLE
Default Date and Date Range

### ISSUE THREAD

**Issue by patrickcho168** [momomods/momomods#58]
1. Set Default Date of Group Query to today's date.
2. Set Date Range of Date Picker to [max(today's date, first day of sem), last day of sem]

**Comment by nicholette** [comment]
- [x] min date
- [x] max date
- [x] default date

**Comment by nicholette** [comment]
what's the max date for the semester?

**Comment by nicholette** [comment]
last date from the semester ends at 2017-01-08 (inc vacation)
