### ISSUE TITLE
UI of editing group confusing

### ISSUE THREAD

**Issue by patrickcho168** [momomods/momomods#62]
When adding friends, can either close or edit. When close, nothing gets updated on backend BUT the user that is added is still shown!
1. Should rename 'close' to 'cancel' and 'edit' to 'confirm' 
2. Should name it as 'Add Friend' rather than 'Find Friends', since friend is immediately added and no accepting of invitation needs to take place.
3. 'x' button should only be shown for new users that are about to be added and not existing members.
4. Rather than say 'Delete Group', should say 'Exit Group' or something like that. Deleting group sounds like you're deleting the whole group and no one should have the ability to do so.
5. If possible, don't allow EDIT to be chosen until an edit is really done. [Not Critical]

**Comment by michelletan** [comment]
Fixed
